

### GET ALL
GET http://127.0.0.1:3000/v2 HTTP/1.1

### GET ONE 
GET http://127.0.0.1:3000/v2/1 HTTP/1.1


### GET SWAGGER
GET http://127.0.0.1:3000/docs HTTP/1.1


### Post 
POST http://127.0.0.1:3000/v2 HTTP/1.1
content-type: application/json

{
    "product": "t-shirt",
    "color": "blue",
    "price": 43,
    "status": true,
    "gross_amount": 20
}


### Delete ONE 
DELETE  http://127.0.0.1:3000/v2/3 HTTP/1.1


### Update one  
PUT http://127.0.0.1:3000/v2/1 HTTP/1.1
content-type: application/json

{
    "product": "ball",
    "color": "red",
    "price": 122,
    "status": false
}

